### ISSUE TITLE
allow text email

### ISSUE THREAD

**Issue by aronatkins** [rich-iannone/quarto-email#6]
HTML output is produced, but there is no option to produce a text alternative.

```json
{
    "rsc_email_body_text": "Ninety-Nine Point Nine Fahrenheit Degrees. Stable now, with rising possibilities."
}
```

Allow text+HTML, text-only, and HTML-only.

**Comment by rich-iannone** [comment]
In https://github.com/rich-iannone/quarto-email/commit/93e01ec4040047e7be21a8100777946abd158707, I've made it so that an `.email-text` class can now be used for a text-only or mixed text/HTML email. Line breaks are preserved by using `pandoc.write(pandoc.Pandoc({ div }), "plain")` internally instead of `pandoc.utils.stringify(div)`. 

```
::: {.email-text}
This is a text-only version of the email.

The report has just a little bit of R code in it. Do you know the txhousing dataset? Well, in the report I provided a subset of that.
:::
```

In the JSON, you get the following:

```
"rsc_email_body_text":"This is a text-only version of the email.\n\nThe report has just a little bit of R code in it. Do you know the\ntxhousing dataset? Well, in the report I provided a subset of that.\n"
```

**Comment by rich-iannone** [comment]
Additionally, just verified that the `rsc_email_body_text` field only appears in the output JSON if there is a div with the `.email-text` class in the Quarto document.

**Comment by rich-iannone** [comment]
Going to close since this seems solved well enough. But please reopen if there's something I missed.
